
include: package:flutter_lints/flutter.yaml
formatter:
  page_width: 120
  trailing_commas: preserve

linter:

  rules:
    prefer_const_constructors: true
    avoid_print: true
    avoid_relative_lib_imports: true 