// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf6UUmN2XyWQD0eqqCIE-AA0pdPdSELDw',
    appId: '1:79488187952:web:eca36297ebf53a9410f7f5',
    messagingSenderId: '79488187952',
    projectId: 'expensetracker-12639',
    authDomain: 'expensetracker-12639.firebaseapp.com',
    storageBucket: 'expensetracker-12639.firebasestorage.app',
    measurementId: 'G-JEQEGGNXM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1h2kBWux0volBIvnVSe_3a0GSikGNh0',
    appId: '1:79488187952:android:d909bacfd42d8f6e10f7f5',
    messagingSenderId: '79488187952',
    projectId: 'expensetracker-12639',
    storageBucket: 'expensetracker-12639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjGgcAwGvdnymm8ScG1zidM74Nj1oA0k',
    appId: '1:79488187952:ios:420f9710f016216b10f7f5',
    messagingSenderId: '79488187952',
    projectId: 'expensetracker-12639',
    storageBucket: 'expensetracker-12639.firebasestorage.app',
    iosBundleId: 'com.salihkocaturk.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjGgcAwGvdnymm8ScG1zidM74Nj1oA0k',
    appId: '1:79488187952:ios:420f9710f016216b10f7f5',
    messagingSenderId: '79488187952',
    projectId: 'expensetracker-12639',
    storageBucket: 'expensetracker-12639.firebasestorage.app',
    iosBundleId: 'com.salihkocaturk.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf6UUmN2XyWQD0eqqCIE-AA0pdPdSELDw',
    appId: '1:79488187952:web:ddb17fda6a0e678610f7f5',
    messagingSenderId: '79488187952',
    projectId: 'expensetracker-12639',
    authDomain: 'expensetracker-12639.firebaseapp.com',
    storageBucket: 'expensetracker-12639.firebasestorage.app',
    measurementId: 'G-KWGHHZ62B6',
  );
}
